### PR TITLE
Basic Server Setup

### PR DESCRIPTION
**Pull request by josephakayesi**
Setup a basic express server with all the required dependencies.

### CODE REVIEW

**Comment by josephakayesi** [comment]
I added a script called 'server' which lets nodemon watch changes in the server.js file.

**Comment by johnotu** [comment]
Nice one @JosephAkayesi. We should isolate server code and keep it separated from other folders/files in root. So,
1. Let's have the server's _package.json_ initialized in folder **server**.
2. Use _yarn_ as package manager to ensure consistency within project.
3. Don't forget to add in the comment or a commit statement, the issue number this PR fixes by following [this guide](https://github.blog/2013-05-14-closing-issues-via-pull-requests/). This is to ensure that issue is closed automatically when this PR is merged.

**Review by johnotu — CHANGES_REQUESTED** [review]
See changes in latest comment

**Comment by josephakayesi** [comment]
@johnotu Okay John. Well noted.

**Comment by josephakayesi** [comment]
@johnotu I am trying to stage the new changes in this pull request. I have made the changes and pushed to the dev branch in my fork. I have also delete the server branch. What I'm I to do next ?

**Pull request closed without merging**
